title: Minimal theme
logo: https://github.com/bhagmuniverse/minimal/blob/master/assets/img/OIG.jpeg
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
